version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@2.0.6
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  aws-cli:
    executor: aws-cli/default
    environment:
      STACK_NAME: sample-stack
      TEMPLATE_FILE: service/infrastructure.yml
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create/Update Stack
          command: |
            set +e
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep $STACK_NAME
            if [ $? -eq 0 ]; then
              aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE
              if [ $? -ne 0 ]; then
                exit 0
              fi
              aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
            else
              aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE
              aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
            fi
  ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "62:6b:2b:c3:67:cd:b7:d0:c0:18:fc:dd:56:f4:94:19"
      - ansible-playbook/install:
          version: "2.9.23"
      - ansible-playbook/playbook:
          playbook: "ansible/playbook.yml"
          inventory: ANSIBLE_INVENTORY
          playbook-options: -u ec2-user --private-key ~/.ssh/id_rsa

workflows:
  sample-workflow:
    jobs:
      - aws-cli
      - ansible-playbook:
          requires:
            - "aws-cli"

