version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  aws-cli:
    executor: aws-cli/default
    environment:
      STACK_NAME: sample-stack
      TEMPLATE_FILE: cloudformation/sample-template.yml
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create/Update Stack
          command: |
            set +e
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep $STACK_NAME
            if [ $? -eq 0 ]; then
              aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE
              if [ $? -ne 0 ]; then
                exit 0
              fi
              aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
            else
              aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://$TEMPLATE_FILE
              aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
            fi

workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
